### ISSUE TITLE
Unsound API ?

### ISSUE THREAD

**Issue by Narsil** [coreylowman/cudarc#33]
Thanks for this lib, I was trying it out and managed to cause illegal address access in the cuda kernel.

Here is the following example (not necessarily the most elegant, I took the matmul example from nvidia).

This example works OK for when running in debug mode and fails in release mode.

My guess is that the slices get dropped too early after optimization (since all ops are asynchronous, I don't think the compiler knows that it should wait for a device synchronization for a and b.

Hereafter the program and stacktrace

```rust
use cudarc::device::{CudaDeviceBuilder, LaunchConfig, LaunchCudaFunction};
use cudarc::jit::{compile_ptx_with_opts, CompileError, CompileOptions};

fn main() -> Result<(), CompileError> {
    let start = std::time::Instant::now();
    let opts = CompileOptions {
        ftz: Some(true),
        prec_div: Some(false),
        prec_sqrt: Some(false),
        fmad: Some(true),
        ..Default::default()
    };

    let ptx = compile_ptx_with_opts(
        "

            __global__ void matmul(float* A, float* B, float* C, int N) {

                int ROW = blockIdx.y*blockDim.y+threadIdx.y;
                int COL = blockIdx.x*blockDim.x+threadIdx.x;

                float tmpSum = 0;

                if (ROW < N && COL < N) {
                    // each thread computes one element of the block sub-matrix
                    for (int i = 0; i < N; i++) {
                        tmpSum += A[ROW * N + i] * B[i * N + COL];
                    }
                }
                // printf(\"pos, (%d, %d) - N %d - value %d\\n\", ROW, COL, N, tmpSum);
                C[ROW * N + COL] = tmpSum;
            }

            ",
        opts,
    )?;
    use core::ffi::CStr;
    let ptx: &CStr = unsafe { CStr::from_ptr(ptx.image().as_ptr()) };
    let ptx: &str = ptx.to_str().unwrap();
    println!("Compilation succeeded!");
    use std::fs::File;
    use std::io::Write;
    let mut file = File::create("matmul.ptx").unwrap();
    file.write_all(ptx.as_bytes()).unwrap();
    println!("Init in {:?}", start.elapsed());
    let dev = CudaDeviceBuilder::new(0)
        .with_ptx_from_file("_Z6matmulPfS_S_i", "./matmul.ptx", &["_Z6matmulPfS_S_i"])
        .build()
        .unwrap();
    println!("Init in {:?}", start.elapsed());

    // "sin_module" is the key used with CudaDeviceBuilder
    let module = dev.get_module("_Z6matmulPfS_S_i").unwrap();

    // "sin_kernel" is the name of the actual function inside the .ptx file
    let f = module.get_fn("_Z6matmulPfS_S_i").unwrap();
    println!("Loaded in {:?}", start.elapsed());

    let a_host = [1.0f32, 2.0, 3.0, 4.0];
    let b_host = [1.0f32, 2.0, 3.0, 4.0];
    let mut c_host = [0.0f32; 4];

    let a_dev = dev.sync_copy(&a_host).unwrap();
    let b_dev = dev.sync_copy(&b_host).unwrap();
    let mut c_dev = dev.sync_copy(&c_host).unwrap();

    let cfg = LaunchConfig {
        block_dim: (2, 2, 1),
        grid_dim: (1, 1, 1),
        shared_mem_bytes: 0,
    };
    unsafe { dev.launch_async(f, cfg, (&a_dev, &b_dev, &mut c_dev, 2)) }.unwrap();

    drop(a_dev);
    drop(b_dev);

    dev.sync_copy_from(&c_dev, &mut c_host).unwrap();
    drop(c_dev);
    println!("Found {:?} in {:?}", c_host, start.elapsed());
    Ok(())
}
```

Stacktrace;

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_ILLEGAL_ADDRESS, "an illegal memory access was encountered")', /home/nicolas/src/cudarc/src/device.rs:204:82
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_ILLEGAL_ADDRESS, "an illegal memory access was encountered")', /home/nicolas/src/cudarc/src/device.rs:204:82
stack backtrace:
   0:     0x55b4bfb5c5fa - std::backtrace_rs::backtrace::libunwind::trace::h196c489280b5a090
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55b4bfb5c5fa - std::backtrace_rs::backtrace::trace_unsynchronized::h13bf778637c29636
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b4bfb5c5fa - std::sys_common::backtrace::_print_fmt::h0f4861fc71bccacd
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55b4bfb5c5fa - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5f011e3cd484ad42
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55b4bfb7ad2e - core::fmt::write::h1524a82fa967022b
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/core/src/fmt/mod.rs:1208:17
   5:     0x55b4bfb5a445 - std::io::Write::write_fmt::ha3d33adc534ae39a
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/io/mod.rs:1682:15
   6:     0x55b4bfb5c3c5 - std::sys_common::backtrace::_print::h11f95f719c502811
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55b4bfb5c3c5 - std::sys_common::backtrace::print::h71adea94b47d00ae
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55b4bfb5da4f - std::panicking::default_hook::{{closure}}::he466417f162d07e8
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panicking.rs:267:22
   9:     0x55b4bfb5d78b - std::panicking::default_hook::hff6ac2c6adb87df1
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panicking.rs:286:9
  10:     0x55b4bfb5e15c - std::panicking::rust_panic_with_hook::hcb61d2700034f188
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panicking.rs:688:13
  11:     0x55b4bfb5def9 - std::panicking::begin_panic_handler::{{closure}}::h44457d7d7214b4ef
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panicking.rs:579:13
  12:     0x55b4bfb5caac - std::sys_common::backtrace::__rust_end_short_backtrace::hf4f789a62590af34
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55b4bfb5dc02 - rust_begin_unwind
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panicking.rs:575:5
  14:     0x55b4bfb3b193 - core::panicking::panic_fmt::h19d66e5282d7808f
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/core/src/panicking.rs:64:14
  15:     0x55b4bfb3b5c3 - core::result::unwrap_failed::h5275d1617160e163
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/core/src/result.rs:1790:5
  16:     0x55b4bfb3bce6 - core::ptr::drop_in_place<cudarc::device::CudaSlice<f32>>::h1e3a20025b0386e7
  17:     0x55b4bfb3c7bf - matmul::main::h96270d3cbc9d8793
  18:     0x55b4bfb3c823 - std::sys_common::backtrace::__rust_begin_short_backtrace::h77c3c7fd1a851eb0
  19:     0x55b4bfb3c843 - std::rt::lang_start::{{closure}}::he524618c01c92a82
  20:     0x55b4bfb576ec - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hee44d3bca815d6cd
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/core/src/ops/function.rs:606:13
  21:     0x55b4bfb576ec - std::panicking::try::do_call::h8e2913788124065e
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panicking.rs:483:40
  22:     0x55b4bfb576ec - std::panicking::try::h460040cf489c3878
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panicking.rs:447:19
  23:     0x55b4bfb576ec - std::panic::catch_unwind::h5e12d45b7905f1f3
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panic.rs:137:14
  24:     0x55b4bfb576ec - std::rt::lang_start_internal::{{closure}}::h53e0b25b0eaaa72b
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/rt.rs:148:48
  25:     0x55b4bfb576ec - std::panicking::try::do_call::h84ed13c66e27b8c7
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panicking.rs:483:40
  26:     0x55b4bfb576ec - std::panicking::try::h9972483dcd03469d
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panicking.rs:447:19
  27:     0x55b4bfb576ec - std::panic::catch_unwind::h56b5ad191546ecc2
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/panic.rs:137:14
  28:     0x55b4bfb576ec - std::rt::lang_start_internal::hc154d6be0270f9da
                               at /rustc/d0dc9efff14ac0a1eeceffd1e605e37eeb8362a0/library/std/src/rt.rs:148:20
  29:     0x55b4bfb3c815 - main
  30:     0x7f40d043c290 - <unknown>
  31:     0x7f40d043c34a - __libc_start_main
  32:     0x55b4bfb3b705 - _start
                               at /build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:115
  33:                0x0 - <unknown>
thread panicked while panicking. aborting.
Aborted (core dumped)
```

Cheers !

**Comment by coreylowman** [comment]
Hello, are you sure that the kernel code doesn't access an illegal memory address? I can't quite tell from looking at the LaunchConfig object if this will have the expected index values.

Can you print out the addresses in the inner loop and post them here?

**Comment by coreylowman** [comment]
> My guess is that the slices get dropped too early after optimization (since all ops are asynchronous, I don't think the compiler knows that it should wait for a device synchronization for a and b.

The drop impl schedules an async drop on the stream, so the actual free on the cuda side should happen after the kernel executes.

**Comment by Narsil** [comment]
Hmmm... I managed to look at the values, it seems `N` within the kernel is `2` in debug mode (correctly) and `32765`(2i32) in release mode. (hence the illegal address).

I don't understand the values I'm seeing..

2u8 -> I get random numbers.
2u32 -> Somehow ranomd values between (`32765` and `32767`)
2i64 -> I get 1 (not illegal address but incorrect pass)

When I look from within the launch_async, and try to unwrap to see back the value, it's indeed those values.

Meaning something doesn't work in  `(&self) as *const $T as *const _c_void` I think, no ?

**Comment by Narsil** [comment]
Ok, I think I have and idea.

```diff
diff --git a/src/device.rs b/src/device.rs
index 2022c8b..c7e3853 100644
--- a/src/device.rs
+++ b/src/device.rs
@@ -559,10 +559,10 @@ unsafe impl<T> IntoKernelParam for &CudaSlice<T> {

 macro_rules! impl_into_kernel_param {
     ($T:ty) => {
-        unsafe impl IntoKernelParam for $T {
+        unsafe impl IntoKernelParam for &$T {
             #[inline(always)]
             fn into_kernel_param(self) -> *mut std::ffi::c_void {
-                (&self) as *const $T as *mut std::ffi::c_void
+                (self) as *const $T as *mut std::ffi::c_void
             }
         }
     };
```

And then launch the kernels by doing `launch_async(..., &n)` instead of `n`. 

Is that correct ?

**Comment by coreylowman** [comment]
Ahh yes good catch! Yeah I recently had changed it away from using `&n` for simplicity, but i see the issue now.

**Comment by coreylowman** [comment]
This is reproducible by running `cargo test --release`

**Comment by coreylowman** [comment]
Okay the fix for this is on main (I also added your code into `examples/` folder). I'll close this for now, but if you find anything else either re-open or open a new issue!

Thanks for reporting!

**Comment by Narsil** [comment]
Thank you ! Cheers !
